name: Submit Sitemap to IndexNow

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]

jobs:
  submit-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Submit sitemap URLs to IndexNow
        uses: jakob-bagterp/index-now-submit-sitemap-urls-action@v1
        with:
          host: lucky-bear-casino.net
          api_key: ${{ secrets.INDEX_NOW_API_KEY }}
          api_key_location: https://lucky-bear-casino.net/${{ secrets.INDEX_NOW_API_KEY }}.txt
          sitemap_locations: https://lucky-bear-casino.net/sitemap.xml
          endpoint: yandex
